### ISSUE TITLE
questions about dpo

### ISSUE THREAD

**Issue by hong-xl** [RLHFlow/Online-RLHF#8]
Hi，I have some questions about dpo: 
1. Is there any reason why choosing Nectar dataset to train offline vanilla dpo rather than using the same dataset as iterative dpo, for a possibly more fair comparison?
2. 3.Have you applied iterative dpo to llama3-70b? When applying iterative dpo to Llama3-70B, what specific details should be paid attention to?

Thanks for your assistance.

**Comment by hong-xl** [comment]
Thanks for your response. If we use all the data from Table 1 to train offline DPO, would it result in better performance? Based on your experience, what kind of data is suitable for training DPO?

**Comment by WeiXiongUST** [comment]
This is a good question. The dataset that is good for reward modeling may not be good for DPO. 

For instance, we use HH-RLHF in reward modeling because it allows the model to evaluate the multi-turn conversation. But it is well known (as verified by > 10 research paper) that DPO trained on HH-RLHF is bad. The nectar re-label these datasets using strong and diverse LLMs to get the responses and is more suitable for DPO training.

**Comment by loss4Wang** [comment]
> This is a good question. The dataset that is good for reward modeling may not be good for DPO.
> 
> For instance, we use HH-RLHF in reward modeling because it allows the model to evaluate the multi-turn conversation. But it is well known (as verified by > 10 research paper) that DPO trained on HH-RLHF is bad. The nectar re-label these datasets using strong and diverse LLMs to get the responses and is more suitable for DPO training.

Thanks for the advice. Could you give some of the research papers discussing about "DPO trained on HH-RLHF is bad" ? I am curious about the reason here.

**Comment by WeiXiongUST** [comment]
see https://arxiv.org/pdf/2309.06657

The vanilla offline DPO largely depends on the data quality. On-policy sampling and online data annotation are the key to the success. This can be shown in a more rigorous way, see theorem 2 and related discussions in https://arxiv.org/pdf/2312.11456. 

Indeed, this is exactly why we wrote this paper: to call for online RLHF instead of distilling GPT4 with offline DPO.
